baseURL = "/"
languageCode = "en-us"
title = "Ecommerce Store"
theme = "ecom"

[params]

titleHeader = "Pallete wetting headline"
subtitle = "Sick Slogan"
headerBuyButton = "Shop Specials"
headerImg = "https://bulma.io/images/bulma-type-white.png"

    [params.bigProduct]
        enable = true
        title = 'Best Selling Product'
        description = 'Product Description'
        details = 'Product details Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis, natus.'
        buttonText = 'Buy My Shit'
        img1 = 'https://wikiki.github.io/images/merry-christmas.jpg'
        img2 = 'https://wikiki.github.io/images/singer.jpg'
        img3 = 'https://wikiki.github.io/images/sushi.jpg'
        img4 = 'https://wikiki.github.io/images/life.jpg'

    [params.topCategories]
        enable = true
            [params.topCategories.left]
                title = 'Do You like This?'
                img = 'https://bulma.io/images/placeholders/128x128.png'
                buttonText = 'Buy Me Baby'
                url = '#'
            [params.topCategories.center]
                title = 'How about this?'
                img = 'https://bulma.io/images/placeholders/128x128.png'
                buttonText = 'Buy Me Now'
                url = '/products'
            [params.topCategories.right]
                title = 'You will love this!'
                img = 'https://bulma.io/images/placeholders/128x128.png'
                buttonText = 'Hurry Baby'
                url = '#'

[permalinks]
  products = "/:section/:filename"


[menu]
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        title = "Blog Section"
        weight = 1
        url = "/blog"

    [[menu.main]]
        identifier = "products"
        name = "Products"
        title = "Our Products"
        weight = 2
        url = '/products'

    [[menu.main]]
        identifier = "bestSellers"
        name = "Best Sellers"
        title = 'The ones people like the most'
        weight = 3
        url = '/best-sellers'
    [[menu.main]]
        identifier = "about"
        name = "About Us"
        title = "Who We Are"
        weight = 4
        url = "/about"
